FROM mcr.microsoft.com/mssql/server:2019-latest

USER root
RUN apt-get update && apt-get install -y curl apt-transport-https gnupg2
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
ENV PATH="$PATH:/opt/mssql-tools/bin"

# Switch back to the default mssql user
USER mssql

# Your other commands...
