version: '3.9'
services:
  mssql:
    platform: "linux/amd64"
    build: .
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_strong!Passw0rd"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "SA", "-P", "Your_strong!Passw0rd", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  schema:
    platform: "linux/amd64"
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssql
    volumes:
      - ./schema.sql:/schema.sql
    command: /bin/bash -c "sleep 20 && /opt/mssql-tools/bin/sqlcmd -S mssql -U SA -P Your_strong!Passw0rd -i /schema.sql"

