services:
 db:
   image: mysql:latest
   container_name: frogCrewContainer
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=frogCrewDatabase
   volumes:
     - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    